version: '3.8'

services:

  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: always
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    environment:
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - user_db
    networks:
      - network


  auth_service:
    image: auth_service
    container_name: auth_service
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    restart: always
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    environment:
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_CACHE_HOST: ${AUTH_CACHE_HOST}
      AUTH_CACHE_PORT: ${AUTH_CACHE_PORT}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      SECRET_CAPTCHA_KEY: ${SECRET_CAPTCHA_KEY}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      SMTP_AUTH_MAIL: ${SMTP_AUTH_MAIL}
      SMTP_AUTH_PASSWORD: ${SMTP_AUTH_PASSWORD}
    depends_on:
      - auth_db
      - auth_cache
    networks:
      - network


  accommodations_service:
    image: accommodations_service
    container_name: accommodations_service
    build:
      context: .
      dockerfile: ./accommodations_service/Dockerfile
    restart: always
    ports:
      - ${ACCOMMODATIONS_SERVICE_PORT}:${ACCOMMODATIONS_SERVICE_PORT}
    environment:
      ACCOMMODATIONS_DB_HOST: ${ACCOMMODATIONS_DB_HOST}
      ACCOMMODATIONS_DB_PORT: ${ACCOMMODATIONS_DB_PORT}
      ACCOMMODATIONS_SERVICE_PORT: ${ACCOMMODATIONS_SERVICE_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      RESERVATIONS_SERVICE_PORT: ${RESERVATIONS_SERVICE_PORT}
      RESERVATIONS_SERVICE_HOST: ${RESERVATIONS_SERVICE_HOST}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - accommodations_db
    networks:
      - network

  reservations_service:
    image: reservations_service
    container_name: reservations_service
    build:
      context: .
      dockerfile: ./reservations_service/Dockerfile
    restart: always
    ports:
      - ${RESERVATIONS_SERVICE_PORT}:${RESERVATIONS_SERVICE_PORT}
    environment:
      RESERVATIONS_DB_HOST: ${RESERVATIONS_DB_HOST}
      RESERVATIONS_DB_PORT: ${RESERVATIONS_DB_PORT}
      RESERVATIONS_SERVICE_PORT: ${RESERVATIONS_SERVICE_PORT}
      RESERVATIONS_SERVICE_HOST: ${RESERVATIONS_SERVICE_HOST}
      APPOINTMENTS_DB_HOST: ${APPOINTMENTS_DB_HOST}
      APPOINTMENTS_DB_PORT: ${APPOINTMENTS_DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - reservations_db
    networks:
      - network


  api_gateway:
    build:
      context: ./api_gateway/
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    networks:
      - network


  user_db:
    image: mongo
    container_name: user_db
    restart: on-failure
    networks:
      - network

  auth_db:
    image: mongo
    container_name: auth_db
    restart: on-failure
    networks:
      - network

  accommodations_db:
    image: mongo
    container_name: accommodations_db
    restart: on-failure
    networks:
      - network

  reservations_db:
    image: cassandra
    container_name: reservations_db
    restart: on-failure
    networks:
      - network

  appointments_db:
    image: mongo
    container_name: appointments_db
    restart: on-failure
    networks:
      - network

  auth_cache:
    image: redis
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${AUTH_CACHE_PORT}:${AUTH_CACHE_PORT}
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - network
    volumes:
      - auth_cache:/data

volumes:

  auth_cache:
    driver: local


networks:
  network:
    driver: bridge