version: '3.8'

services:

  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: always
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    environment:
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
    depends_on:
      - user_db
    networks:
      - network


  auth_service:
    image: auth_service
    container_name: auth_service
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    restart: always
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    environment:
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
    depends_on:
      - auth_db
    networks:
      - network


  accommodations_service:
    image: accommodations_service
    container_name: accommodations_service
    build:
      context: .
      dockerfile: ../Airbnb-Project/Airbnb-Backend/accommodations_service/Dockerfile
    restart: always
    ports:
      - ${ACCOMMODATIONS_SERVICE_PORT}:${ACCOMMODATIONS_SERVICE_PORT}
    environment:
      ACCOMMODATIONS_DB_HOST: ${ACCOMMODATIONS_DB_HOST}
      ACCOMMODATIONS_DB_PORT: ${ACCOMMODATIONS_DB_PORT}
      ACCOMMODATIONS_SERVICE_PORT: ${ACCOMMODATIONS_SERVICE_PORT}
    depends_on:
      - accommodations_db
    networks:
      - network


  api_gateway:
    build:
      context: ./api_gateway/
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    networks:
      - network


  user_db:
    image: mongo
    container_name: user_db
    restart: on-failure
    networks:
      - network

  auth_db:
    image: mongo
    container_name: auth_db
    restart: on-failure
    networks:
      - network

  accommodations_db:
    image: cassandra
    container_name: accommodations_db
    restart: on-failure
    networks:
      - network


networks:
  network:
    driver: bridge