version: '3.8'

services:

  notification_service:
    image: notification_service
    container_name: notification_service
    build:
      context: .
      dockerfile: ./notification_service/Dockerfile
    restart: always
    ports:
      - ${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}
    environment:
      NOTIFICATION_DB_HOST: ${NOTIFICATION_DB_HOST}
      NOTIFICATION_DB_PORT: ${NOTIFICATION_DB_PORT}
      NOTIFICATION_SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      SMTP_AUTH_MAIL: ${SMTP_AUTH_MAIL}
      SMTP_AUTH_PASSWORD: ${SMTP_AUTH_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      JAEGER_ADDRESS: ${JAEGER_ADDRESS}
    depends_on:
      - notification_db
      - jaeger
    networks:
      - network
    dns:
      - 8.8.8.8

  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: always
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    environment:
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      RESERVATIONS_SERVICE_HOST: ${RESERVATIONS_SERVICE_HOST}
      RESERVATIONS_SERVICE_PORT: ${RESERVATIONS_SERVICE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      JAEGER_ADDRESS: ${JAEGER_ADDRESS}
    depends_on:
      - user_db
      - jaeger
    networks:
      - network


  auth_service:
    image: auth_service
    container_name: auth_service
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    restart: always
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    environment:
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_CACHE_HOST: ${AUTH_CACHE_HOST}
      AUTH_CACHE_PORT: ${AUTH_CACHE_PORT}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      SECRET_CAPTCHA_KEY: ${SECRET_CAPTCHA_KEY}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      RESERVATIONS_SERVICE_PORT: ${RESERVATIONS_SERVICE_PORT}
      RESERVATIONS_SERVICE_HOST: ${RESERVATIONS_SERVICE_HOST}
      ACCOMMODATIONS_SERVICE_PORT: ${ACCOMMODATIONS_SERVICE_PORT}
      ACCOMMODATIONS_SERVICE_HOST: ${ACCOMMODATIONS_SERVICE_HOST}
      SMTP_AUTH_MAIL: ${SMTP_AUTH_MAIL}
      SMTP_AUTH_PASSWORD: ${SMTP_AUTH_PASSWORD}
      JAEGER_ADDRESS: ${JAEGER_ADDRESS}
    depends_on:
      - auth_db
      - auth_cache
      - jaeger
    networks:
      - network
    dns:
      - 8.8.8.8


  accommodations_service:
    image: accommodations_service
    container_name: accommodations_service
    build:
      context: .
      dockerfile: ./accommodations_service/Dockerfile
    restart: always
    ports:
      - ${ACCOMMODATIONS_SERVICE_PORT}:${ACCOMMODATIONS_SERVICE_PORT}
    environment:
      ACCOMMODATIONS_DB_HOST: ${ACCOMMODATIONS_DB_HOST}
      ACCOMMODATIONS_DB_PORT: ${ACCOMMODATIONS_DB_PORT}
      ACCOMMODATIONS_SERVICE_PORT: ${ACCOMMODATIONS_SERVICE_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      RESERVATIONS_SERVICE_PORT: ${RESERVATIONS_SERVICE_PORT}
      RESERVATIONS_SERVICE_HOST: ${RESERVATIONS_SERVICE_HOST}
      NOTIFICATION_SERVICE_HOST: ${NOTIFICATION_SERVICE_HOST}
      NOTIFICATION_SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      JAEGER_ADDRESS: ${JAEGER_ADDRESS}
      HDFS_URI: namenode:9000
    volumes:
      - ./files:/usr/bin/files
    depends_on:
      namenode:
        condition: service_healthy
      datanode1:
        condition: service_healthy
      datanode2:
        condition: service_healthy
      datanode3:
        condition: service_healthy
    extra_hosts:
      - "namenode:172.18.0.4"
      - "namenode:172.18.0.5"
      - "namenode:172.18.0.2"
      - "namenode:172.18.0.3"
    networks:
      - network


  reservations_service:
    image: reservations_service
    container_name: reservations_service
    build:
      context: .
      dockerfile: ./reservations_service/Dockerfile
    restart: always
    ports:
      - ${RESERVATIONS_SERVICE_PORT}:${RESERVATIONS_SERVICE_PORT}
    environment:
      RESERVATIONS_DB_HOST: ${RESERVATIONS_DB_HOST}
      RESERVATIONS_DB_PORT: ${RESERVATIONS_DB_PORT}
      RESERVATIONS_SERVICE_PORT: ${RESERVATIONS_SERVICE_PORT}
      RESERVATIONS_SERVICE_HOST: ${RESERVATIONS_SERVICE_HOST}
      ACCOMMODATIONS_SERVICE_HOST: ${ACCOMMODATIONS_SERVICE_HOST}
      ACCOMMODATIONS_SERVICE_PORT: ${ACCOMMODATIONS_SERVICE_PORT}
      APPOINTMENTS_DB_HOST: ${APPOINTMENTS_DB_HOST}
      APPOINTMENTS_DB_PORT: ${APPOINTMENTS_DB_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      NOTIFICATION_SERVICE_HOST: ${NOTIFICATION_SERVICE_HOST}
      NOTIFICATION_SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT}
      JAEGER_ADDRESS: ${JAEGER_ADDRESS}
      # depends_on:
      # - reservations_db
    # Pokretanje reservation servisa tek kada je baza uspesno pokrenuta
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      jaeger:
        condition: service_started
      reservations_db:
        condition: service_healthy

    networks:
      - network


  api_gateway:
    build:
      context: ./api_gateway/
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    depends_on:
      - reservations_service
      - auth_service
      - user_service
      - notification_service
      - accommodations_service
    networks:
      - network


  notification_db:
    image: mongo
    container_name: notification_db
    restart: on-failure
    networks:
      - network

  user_db:
    image: mongo
    container_name: user_db
    restart: on-failure
    networks:
      - network

  auth_db:
    image: mongo
    container_name: auth_db
    restart: on-failure
    networks:
      - network

  accommodations_db:
    image: mongo
    container_name: accommodations_db
    restart: on-failure
    networks:
      - network


  reservations_db:
    image: cassandra
    container_name: reservations_db
    restart: on-failure
    # Healthcheck za cassandra bazu podataka
    # Docker healtcheck - checks if database is "alive"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 15s
      timeout: 5s
      retries: 15
    # Preporuka da dodatno podesite healtcheck i za ostale baze
    # (healtcheck provere mozete naci u primerima sa vezbi)
    # Dodatno, bilo bi dobro da konfigurisete volumes za svaku bazu
    # kako biste imali sacuvane podatke i izmedju dva pokretanja
    # recimo:
    volumes:
      - reservations_db_store:/var/lib/cassandra/data
    # I zatim navodite u volumes
    networks:
      - network

  appointments_db:
    image: mongo
    container_name: appointments_db
    restart: on-failure
    networks:
      - network

  auth_cache:
    image: redis
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${AUTH_CACHE_PORT}:${AUTH_CACHE_PORT}
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - network
    volumes:
      - auth_cache:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - network

  collector:
    image: otel/opentelemetry-collector:0.69.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./api_gateway/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - network

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hdfs.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hdfs.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hdfs.env

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hdfs.env

volumes:
  # Volume na koji se povezuje reservations_db baza podataka
  reservations_db_store:
  auth_cache:
    driver: local
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:

networks:
  network:
    driver: bridge